### ISSUE TITLE
Workaround for windows CMake not having any executable but dot.

### ISSUE THREAD

**Issue by dschult** [pygraphviz/pygraphviz#289] opened 2020-12-24 07:50 UTC
The way Graphviz handles which program is used is to either 1) look at the argv0 name, or 2) look at the `-Kneato` flag in the arguments. [The issue on graphviz that discusses this](https://gitlab.com/graphviz/graphviz/-/issues/1753#note_372074070) mentions this fact and the following comments suggest that they are working on a fix to allow method 1) to work.  But in the meantime, we should be able to get it to work with method 2).  It requires us to no longer rely on method 1) to call the program at the command line. We currently figure out which program to run, so we can choose whether to use method 1) or 2) pretty easily.  If we always use method 2) we should be good on any system.

Idea:  try always running the code as `dot` but use a `-Kprog` flag to tell it which tool to use.
I think this only requires changes to `AGraph._run_prog`. We should check for a `-K` arg and if present make sure it is the same as the "prog" requested. If not, we can choose whether to raise an exception or let the `-k` flag overrule. If no `-K` flag is in `args` then we add one: `args += " -K" + prog`.
The set `prog` to `dot` and run the code already in `AGraph._run_prog`.

Might not work, but probably worth a try.

**Comment by jarrodmillman** [comment] 2020-12-25 18:00
Let's hold off on this for a tiny bit.  I want to investigate how soon this will be fixed upstream.

**Comment by jarrodmillman** [comment] 2021-01-18 19:51
It looks like this will no longer be necessary as the issue is fixed with the upcoming version 2.46.0 of Graphviz:
https://gitlab.com/graphviz/graphviz/-/merge_requests/1672

**Closed by jarrodmillman** 2021-01-18 19:51 UTC
