### ISSUE TITLE
Symbol not found: _Agdirected   Referenced when importing (Mac OS Big Sur)

### ISSUE THREAD

**Issue by gdberrio** [pygraphviz/pygraphviz#342] opened 2021-03-31 20:03 UTC
Hello,

I've been trying to install pygraphviz on a MacOS Big Sur (M1 under emulation), and I'm getting the following error:

```python
➜ ipython
Python 3.8.5 (default, Sep  4 2020, 02:22:02)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.19.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import pygraphviz
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-e9ec173dab0d> in <module>
----> 1 import pygraphviz

~/anaconda3/lib/python3.8/site-packages/pygraphviz/__init__.py in <module>
     22 __version__ = "1.7"
     23
---> 24 from .agraph import AGraph, Node, Edge, Attribute, ItemAttribute, DotError
     25
     26 __all__ = ["AGraph", "Node", "Edge", "Attribute", "ItemAttribute", "DotError"]

~/anaconda3/lib/python3.8/site-packages/pygraphviz/agraph.py in <module>
     13 import io
     14
---> 15 from . import graphviz as gv
     16
     17 _DEFAULT_ENCODING = "UTF-8"

~/anaconda3/lib/python3.8/site-packages/pygraphviz/graphviz.py in <module>
     11 # Import the low-level C/C++ module
     12 if __package__ or "." in __name__:
---> 13     from . import _graphviz
     14 else:
     15     import _graphviz

ImportError: dlopen(/Users/guilhermediaz-berrio/anaconda3/lib/python3.8/site-packages/pygraphviz/_graphviz.cpython-38-darwin.so, 2): Symbol not found: _Agdirected
  Referenced from: /Users/guilhermediaz-berrio/anaconda3/lib/python3.8/site-packages/pygraphviz/_graphviz.cpython-38-darwin.so
  Expected in: flat namespace
 in /Users/guilhermediaz-berrio/anaconda3/lib/python3.8/site-packages/pygraphviz/_graphviz.cpython-38-darwin.so
```

I have installed graphviz via Homebrew, and ran pip with the following command:

```
pip install --global-option=build_ext \
              --global-option="-I/opt/homebrew/Cellar/graphviz/2.47.0/include/" \
              --global-option="-L/opt/homebrew/Cellar/graphviz/2.47.0/lib/" \
              pygraphviz
```

This resulted in a successful installation, but I cannot import pygraphviz.

**Comment by rossbar** [comment] 2021-03-31 20:42
Thanks for the report... would you happen to a log from the pip install build_ext command as well?

**Comment by gdberrio** [comment] 2021-03-31 22:17
Hello,

```
pip install --global-option=build_ext \
              --global-option="-I/opt/homebrew/Cellar/graphviz/2.47.0/include/" \
              --global-option="-L/opt/homebrew/Cellar/graphviz/2.47.0/lib/" \
              pygraphviz
/Users/guilhermediaz-berrio/anaconda3/lib/python3.8/site-packages/pip/_internal/commands/install.py:235: UserWarning: Disabling all use of wheels due to the use of --build-option / --global-option / --install-option.
  cmdoptions.check_install_build_global(options)
Collecting pygraphviz
  Using cached pygraphviz-1.7.zip (118 kB)
Skipping wheel build for pygraphviz, due to binaries being disabled for it.
Installing collected packages: pygraphviz
    Running setup.py install for pygraphviz ... done
Successfully installed pygraphviz-1.7
```

**Comment by rossbar** [comment] 2021-03-31 23:59
Ah, my mistake - I had been hoping that the `--global-option=build_ext` would give the full compilation output but I guess you only get that when building from source via `setup.py`.

There's not a lot to go on here, but the first things I would check are:
 1) The Graphviz installation - is Graphviz itself working as expected?
 2) The fact that it builds without error but fails at import time indicates that there may be something wrong with runtime library resolution. I'd try to eliminate more likely causes first before trying to chase down what's happening from this perspective.

The only other thing that comes to mind from the available info is that it looks like you're building with an anaconda python. If there are multiple versions of Python on your system it would be useful to also verify that you are using the interpreter that you expect for installing/running everything.

**Comment by gdberrio** [comment] 2021-04-01 07:01
Regarding your points:
1. I tested Graphviz, and it is working as expected.
2. I'm using the Anaconda ipython (and installed using the Anaconda pip) so I should not have an issue?

```
➜ which pip
/Users/guilhermediaz-berrio/anaconda3/bin/pip
(base)
~ via 🅒 base
➜ which python
/Users/guilhermediaz-berrio/anaconda3/bin/python
(base)
~ via 🅒 base
➜ which ipython
/Users/guilhermediaz-berrio/anaconda3/bin/ipython
(base)
```

For reference, I was having the same issue before installing Anaconda.

**Comment by rossbar** [comment] 2021-04-01 17:37
Is it possible that you have multiple versions of Graphviz installed? Perhaps the libs pointed to during installation ends up being different than what gets picked up at runtime, which could happen if there are multiple Graphviz versions installed.

Along these lines: manually specifying header and include dirs shouldn't be necessary for Graphviz installed via homebrew. What happens if you follow [this procedure](https://pygraphviz.github.io/documentation/stable/install.html#homebrew) in a clean environment?

**Comment by gdberrio** [comment] 2021-04-03 16:05
When I ran that procedure on a clean environment I got the compile error, complaining about the lack of the header files:

```
Collecting pygraphviz
  Downloading pygraphviz-1.7.zip (118 kB)
     |████████████████████████████████| 118 kB 6.3 MB/s
Building wheels for collected packages: pygraphviz
  Building wheel for pygraphviz (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/guilhermediaz-berrio/anaconda3/envs/graphviz/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/xk/tb_jfngd2nz4f4g4ncmt_wz80000gn/T/pip-install-dz5fbm6_/pygraphviz_ed914238cba14da899a3a6c6273a81df/setup.py'"'"'; __file__='"'"'/private/var/folders/xk/tb_jfngd2nz4f4g4ncmt_wz80000gn/T/pip-install-dz5fbm6_/pygraphviz_ed914238cba14da899a3a6c6273a81df/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/xk/tb_jfngd2nz4f4g4ncmt_wz80000gn/T/pip-wheel-wkmsawa8
       cwd: /private/var/folders/xk/tb_jfngd2nz4f4g4ncmt_wz80000gn/T/pip-install-dz5fbm6_/pygraphviz_ed914238cba14da899a3a6c6273a81df/
  Complete output (71 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.9-x86_64-3.8
  creating build/lib.macosx-10.9-x86_64-3.8/pygraphviz
  copying pygraphviz/scraper.py -> build/lib.macosx-10.9-x86_64-3.8/pygraphviz
  copying pygraphviz/graphviz.py -> build/lib.macosx-10.9-x86_64-3.8/pygraphviz
  copying pygraphviz/__init__.py -> build/lib.macosx-10.9-x86_64-3.8/pygraphviz
  copying pygraphviz/agraph.py -> build/lib.macosx-10.9-x86_64-3.8/pygraphviz
  copying pygraphviz/testing.py -> build/lib.macosx-10.9-x86_64-3.8/pygraphviz
  creating build/lib.macosx-10.9-x86_64-3.8/pygraphviz/tests
  copying pygraphviz/tests/test_unicode.py -> build/lib.macosx-10.9-x86_64-3.8/pygraphviz/tests
  copying pygraphviz/tests/test_scraper.py -> build/lib.macosx-10.9-x86_64-3.8/pygraphviz/tests
  copying pygraphviz/tests/test_readwrite.py -> build/lib.macosx-10.9-x86_64-3.8/pygraphviz/tests
  copying pygraphviz/tests/test_string.py -> build/lib.macosx-10.9-x86_64-3.8/pygraphviz/tests
  copying pygraphviz/tests/__init__.py -> build/lib.macosx-10.9-x86_64-3.8/pygraphviz/tests
  copying pygraphviz/tests/test_html.py -> build/lib.macosx-10.9-x86_64-3.8/pygraphviz/tests
  copying pygraphviz/tests/test_node_attributes.py -> build/lib.macosx-10.9-x86_64-3.8/pygraphviz/tests
  copying pygraphviz/tests/test_drawing.py -> build/lib.macosx-10.9-x86_64-3.8/pygraphviz/tests
  copying pygraphviz/tests/test_subgraph.py -> build/lib.macosx-10.9-x86_64-3.8/pygraphviz/tests
  copying pygraphviz/tests/test_close.py -> build/lib.macosx-10.9-x86_64-3.8/pygraphviz/tests
  copying pygraphviz/tests/test_edge_attributes.py -> build/lib.macosx-10.9-x86_64-3.8/pygraphviz/tests
  copying pygraphviz/tests/test_clear.py -> build/lib.macosx-10.9-x86_64-3.8/pygraphviz/tests
  copying pygraphviz/tests/test_layout.py -> build/lib.macosx-10.9-x86_64-3.8/pygraphviz/tests
  copying pygraphviz/tests/test_attribute_defaults.py -> build/lib.macosx-10.9-x86_64-3.8/pygraphviz/tests
  copying pygraphviz/tests/test_graph.py -> build/lib.macosx-10.9-x86_64-3.8/pygraphviz/tests
  running egg_info
  writing pygraphviz.egg-info/PKG-INFO
  writing dependency_links to pygraphviz.egg-info/dependency_links.txt
  writing top-level names to pygraphviz.egg-info/top_level.txt
  reading manifest file 'pygraphviz.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching '*.png' under directory 'doc'
  warning: no files found matching '*.txt' under directory 'doc'
  warning: no files found matching '*.css' under directory 'doc'
  warning: no previously-included files matching '*~' found anywhere in distribution
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  warning: no previously-included files matching '.svn' found anywhere in distribution
  no previously-included directories found matching 'doc/build'
  writing manifest file 'pygraphviz.egg-info/SOURCES.txt'
  copying pygraphviz/graphviz.i -> build/lib.macosx-10.9-x86_64-3.8/pygraphviz
  copying pygraphviz/graphviz_wrap.c -> build/lib.macosx-10.9-x86_64-3.8/pygraphviz
  running build_ext
  building 'pygraphviz._graphviz' extension
  creating build/temp.macosx-10.9-x86_64-3.8
  creating build/temp.macosx-10.9-x86_64-3.8/pygraphviz
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/guilhermediaz-berrio/anaconda3/envs/graphviz/include -arch x86_64 -I/Users/guilhermediaz-berrio/anaconda3/envs/graphviz/include -arch x86_64 -I/Users/guilhermediaz-berrio/anaconda3/envs/graphviz/include/python3.8 -c pygraphviz/graphviz_wrap.c -o build/temp.macosx-10.9-x86_64-3.8/pygraphviz/graphviz_wrap.o
  pygraphviz/graphviz_wrap.c:1756:7: warning: 'tp_print' is deprecated [-Wdeprecated-declarations]
        0,                                    /* tp_print */
        ^
  /Users/guilhermediaz-berrio/anaconda3/envs/graphviz/include/python3.8/cpython/object.h:260:5: note: 'tp_print' has been explicitly marked deprecated here
      Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *, int);
      ^
  /Users/guilhermediaz-berrio/anaconda3/envs/graphviz/include/python3.8/pyport.h:515:54: note: expanded from macro 'Py_DEPRECATED'
  #define Py_DEPRECATED(VERSION_UNUSED) __attribute__((__deprecated__))
                                                       ^
  pygraphviz/graphviz_wrap.c:1923:7: warning: 'tp_print' is deprecated [-Wdeprecated-declarations]
        0,                                    /* tp_print */
        ^
  /Users/guilhermediaz-berrio/anaconda3/envs/graphviz/include/python3.8/cpython/object.h:260:5: note: 'tp_print' has been explicitly marked deprecated here
      Py_DEPRECATED(3.8) int (*tp_print)(PyObject *, FILE *, int);
      ^
  /Users/guilhermediaz-berrio/anaconda3/envs/graphviz/include/python3.8/pyport.h:515:54: note: expanded from macro 'Py_DEPRECATED'
  #define Py_DEPRECATED(VERSION_UNUSED) __attribute__((__deprecated__))
                                                       ^
  pygraphviz/graphviz_wrap.c:2711:10: fatal error: 'graphviz/cgraph.h' file not found
  #include "graphviz/cgraph.h"
           ^~~~~~~~~~~~~~~~~~~
  2 warnings and 1 error generated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for pygraphviz
  Running setup.py clean for pygraphviz
Failed to build pygraphviz
```

**Comment by rossbar** [comment] 2021-04-03 17:55
Have you tried only specifying the `-I` flag via `global-options`?

**Comment by gdberrio** [comment] 2021-04-03 22:36
never used that flag. How would I do that?

**Comment by rossbar** [comment] 2021-04-04 05:20
I just meant run the command that you had originally posted, but leave out the explicit library path specification, i.e. something like:

`pip install --global-option=build_ext --global-option="-I/opt/homebrew/Cellar/graphviz/2.47.0/include/"  pygraphviz`

This is kind of a shot in the dark based on the hypothesis that there are multiple versions of GraphViz installed, and that the libs being picked up are different at build and run time.

**Comment by johnnyleebio** [comment] 2021-04-21 03:38
I tried doing this with only the -I flag and unfortunately, no luck. I'm still getting a related import error here. 

`(nighres) -bash-4.2$ pip install --global-option=build_ext --global-option="-I/usr/include/graphviz" pygraphviz
/ifshome/jolee/miniconda/envs/nighres/lib/python3.9/site-packages/pip/_internal/commands/install.py:234: UserWarning: Disabling all use of wheels due to the use of --build-option / --global-option / --install-option.
  cmdoptions.check_install_build_global(options)
Collecting pygraphviz
  Using cached pygraphviz-1.7.zip (118 kB)
Skipping wheel build for pygraphviz, due to binaries being disabled for it.
Installing collected packages: pygraphviz
    Running setup.py install for pygraphviz ... done
Successfully installed pygraphviz-1.7`

`In [1]: import pygraphviz
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-e9ec173dab0d> in <module>
----> 1 import pygraphviz

~/miniconda/envs/nighres/lib/python3.9/site-packages/pygraphviz/__init__.py in <module>
     22 __version__ = "1.7"
     23 
---> 24 from .agraph import AGraph, Node, Edge, Attribute, ItemAttribute, DotError
     25 
     26 __all__ = ["AGraph", "Node", "Edge", "Attribute", "ItemAttribute", "DotError"]

~/miniconda/envs/nighres/lib/python3.9/site-packages/pygraphviz/agraph.py in <module>
     13 import io
     14 
---> 15 from . import graphviz as gv
     16 
     17 _DEFAULT_ENCODING = "UTF-8"

~/miniconda/envs/nighres/lib/python3.9/site-packages/pygraphviz/graphviz.py in <module>
     11 # Import the low-level C/C++ module
     12 if __package__ or "." in __name__:
---> 13     from . import _graphviz
     14 else:
     15     import _graphviz

ImportError: /ifshome/jolee/miniconda/envs/nighres/lib/python3.9/site-packages/pygraphviz/_graphviz.cpython-39-x86_64-linux-gnu.so: undefined symbol: gvFreeRenderData`

**Comment by rossbar** [comment] 2021-04-26 16:51
@johnnyleebio the import error you're seeing is actually different than the original one. Have you tried also specifying the library path explicitly as recommended [here](https://pygraphviz.github.io/documentation/stable/install.html)? The required installation steps will depend on how GraphViz was installed.

**Comment by johnnyleebio** [comment] 2021-04-26 19:05
Yes! Also no luck with specifying paths to the graphviz installation that I have on my computer. @gdberrio did you find anything that could resolve your import issue?

**Comment by johnnyleebio** [comment] 2021-04-27 05:07
I installed pygraphviz == 1.6 instead of 1.7, and it ended up working for me. I believe I had an older version of GraphViz installed on my Unix system that was causing the issue. This may help others possibly who are running into import errors.

**Comment by rossbar** [comment] 2021-05-03 18:24
> I believe I had an older version of GraphViz installed on my Unix system that was causing the issue. 

Thanks for the info, I think you're correct that this is very likely related - note that the pygraphviz installation procedures have only recently been added/tested with GraphViz v2.46 and above, so it's very possible there are still platform-specific problems w/ older Graphviz.

I'm going to close this issue now since we have multiple discussion threads going on. If issues persist or there are mac installation issues that you think may be related, please open a new issue with updated info about the errors and system.

**Closed by rossbar** 2021-05-03 18:24 UTC

**Comment by cmariscalvo** [comment] 2022-06-20 14:25
Hi everyone, 
I had the same problem as @johnnyleebio but I could not fix it installing a different version of Graphviz. My current version is newer than v.2.46 and i am using the latest version of pygraphviz (1.9). 

The problem is the following one: 
![image](https://user-images.githubusercontent.com/101839447/174622974-0d6479d7-bb4e-4ae5-987a-ffd9c770c1ea.png)
As you can see, no _graphviz file has been found in relative folder, whose files are shown in the next image: 
![image](https://user-images.githubusercontent.com/101839447/174623207-99b7474f-5f66-46da-8deb-a1a48d222293.png)
I do not understand why I do not have that file in my folder. 

Thanks!

**Comment by yyf0324** [comment] 2023-03-28 13:39
> I installed pygraphviz == 1.6 instead of 1.7, and it ended up working for me. I believe I had an older version of GraphViz installed on my Unix system that was causing the issue. This may help others possibly who are running into import errors.

Hi,
Could you please tell me how you installed pygraphviz == 1.6 instead of 1.7? Thanks!

**Comment by flipdazed** [comment] 2023-09-17 20:49
Current version 9.0.0 (released 9 days ago) gives this error on import

```
ImportError: dlopen(.../lib/python3.8/site-packages/pygraphviz/_graphviz.cpython-38-darwin.so, 0x0002): symbol not found in flat namespace '_Agdirected'
```

**Comment by MridulS** [comment] 2023-09-18 21:28
@flipdazed could you please open a new issue with the exact versions of pygraphviz, graphviz, operating system and how you installed graphviz and pygraphviz? Thanks!

**Comment by Abdulrahman-97** [comment] 2024-10-02 09:59
I spent hours trying to solve this issue, then I eventually did. Here is what I did:

- Install graphviz using ports (It didn't work using homebrew for some reason)
- Install pygraphviz
`pip install --config-settings="--global-option=build_ext" \
                  --config-settings="--global-option=-I/opt/local/include/" \
                  --config-settings="--global-option=-L/opt/local/lib/" \
                  pygraphviz --no-cache-dir`
                  
- Versions:
 - Mac OS 14.6.1 (Apple M1 Pro)
 - pygraphviz 1.14
