### ISSUE TITLE
py3.5: pygraphviz.tests.test_clear.test_clear_node_with_attributes ... Segmentation fault

### ISSUE THREAD

**Issue by sandrotosi** [pygraphviz/pygraphviz#84] opened 2016-01-03 02:10 UTC
that's rather important: with python 3.5 "plain"  flavor (not -dbg) I got this SIGSEGV when running the test suite:

```
pygraphviz.tests.test_clear.test_clear_node_with_attributes ... Segmentation fault
```

how can I debug it?

**Comment by hagberg** [comment] 2016-01-03 17:19
That is pretty bad.  It may be that with Python3.5 we need an updated swig wrapper?  Or could be some other bug now exposed.  I'll see if I can figure out what is happening.

**Comment by sandrotosi** [comment] 2016-01-03 21:50
let me know if I can help with the debugging: it's pretty easy for me to re-run the build process (with some changes)

**Comment by FRidh** [comment] 2016-02-10 11:21
Note that the same issue also occurs with Python 3.4.
We also get a segmentation fault with PyPy.
```
running build_ext
copying build/lib.linux-x86_64-2.7/pygraphviz/_graphviz.pypy-26.so -> pygraphviz
/nix/store/hkqi4dqipkhwrrv08640i4k1lzkdiqlq-pypy4.0-nose-1.3.7/site-packages/nose/config.py:264: RuntimeWarning: Option 'with-doctest' in config file 'setup.cfg' ignored: excluded by runtime environment
  warn(msg, RuntimeWarning)
/nix/store/hkqi4dqipkhwrrv08640i4k1lzkdiqlq-pypy4.0-nose-1.3.7/site-packages/nose/config.py:264: RuntimeWarning: Option 'with-id' in config file 'setup.cfg' ignored: excluded by runtime environment
  warn(msg, RuntimeWarning)
/nix/store/hkqi4dqipkhwrrv08640i4k1lzkdiqlq-pypy4.0-nose-1.3.7/site-packages/nose/config.py:264: RuntimeWarning: Option 'doctest-extension' in config file 'setup.cfg' ignored: excluded by runtime environment
  warn(msg, RuntimeWarning)
pygraphviz.tests.test_attribute_defaults.test_default_attributes ... Fatal error in cpyext, CPython compatibility layer, calling PyFile_AsFile
Either report a bug or consider not using this particular extension
<SystemError object at 0x7ffff67c4d88>
RPython traceback:
  File "pypy_module_cpyext_pyobject.c", line 485, in make_ref
  File "rpython_rtyper_lltypesystem_rordereddict.c", line 2727, in ll_dict_getitem_with_hash__dicttablePtr_objectPt
/nix/store/x4pl766z2xfzvdcagiq0fb5hxl9z8b61-stdenv/setup: line 842:   265 Segmentation fault 
```

**Comment by hagberg** [comment] 2016-02-10 21:21
I can't reproduce this error with CPython (see below for passing test).

Is there is working Swig support for PyPy?  Otherwise there is no chance this is going to work there.

```
[aric@aric-virtual-machine pygraphviz-1.3.1]$ dot -V 
dot - graphviz version 2.38.0 (20140413.2041)
```
```
[aric@aric-virtual-machine pygraphviz-1.3.1]$ python3.5 setup.py test
running test
Searching for doctest-ignore-unicode>=0.1.0
Reading https://pypi.python.org/simple/doctest-ignore-unicode/
Best match: doctest-ignore-unicode 0.1.2
Downloading https://pypi.python.org/packages/source/d/doctest-ignore-unicode/doctest-ignore-unicode-0.1.2.tar.gz#md5=ba64fe1ef48e8ed68d9ac9a9a03d0c65
Processing doctest-ignore-unicode-0.1.2.tar.gz
Writing /tmp/easy_install-x5mp7a7i/doctest-ignore-unicode-0.1.2/setup.cfg
Running doctest-ignore-unicode-0.1.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-x5mp7a7i/doctest-ignore-unicode-0.1.2/egg-dist-tmp-x90kbpmi
creating /home/aric/localtmp/pygraphviz-1.3.1/.eggs/doctest_ignore_unicode-0.1.2-py3.5.egg
Extracting doctest_ignore_unicode-0.1.2-py3.5.egg to /home/aric/localtmp/pygraphviz-1.3.1/.eggs

Installed /home/aric/localtmp/pygraphviz-1.3.1/.eggs/doctest_ignore_unicode-0.1.2-py3.5.egg
Searching for nose>=0.10.1
Reading https://pypi.python.org/simple/nose/
Best match: nose 1.3.7
Downloading https://pypi.python.org/packages/source/n/nose/nose-1.3.7.tar.gz#md5=4d3ad0ff07b61373d2cefc89c5d0b20b
Processing nose-1.3.7.tar.gz
Writing /tmp/easy_install-llmsty5r/nose-1.3.7/setup.cfg
Running nose-1.3.7/setup.py -q bdist_egg --dist-dir /tmp/easy_install-llmsty5r/nose-1.3.7/egg-dist-tmp-vxnxe8na
no previously-included directories found matching 'doc/.build'
creating /home/aric/localtmp/pygraphviz-1.3.1/.eggs/nose-1.3.7-py3.5.egg
Extracting nose-1.3.7-py3.5.egg to /home/aric/localtmp/pygraphviz-1.3.1/.eggs

Installed /home/aric/localtmp/pygraphviz-1.3.1/.eggs/nose-1.3.7-py3.5.egg
running egg_info
writing top-level names to pygraphviz.egg-info/top_level.txt
writing pygraphviz.egg-info/PKG-INFO
writing dependency_links to pygraphviz.egg-info/dependency_links.txt
reading manifest file 'pygraphviz.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '*~' found anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '.svn' found anywhere in distribution
no previously-included directories found matching 'doc/build'
writing manifest file 'pygraphviz.egg-info/SOURCES.txt'
running build_ext
building 'pygraphviz._graphviz' extension
creating build
creating build/temp.linux-x86_64-3.5
creating build/temp.linux-x86_64-3.5/pygraphviz
gcc -pthread -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/local/include/python3.5m -c pygraphviz/graphviz_wrap.c -o build/temp.linux-x86_64-3.5/pygraphviz/graphviz_wrap.o
pygraphviz/graphviz_wrap.c: In function ‘agattr_label’:
pygraphviz/graphviz_wrap.c:3321:5: warning: return makes integer from pointer without a cast [enabled by default]
     return agattr(g, kind, name, val);
     ^
creating build/lib.linux-x86_64-3.5
creating build/lib.linux-x86_64-3.5/pygraphviz
gcc -pthread -shared build/temp.linux-x86_64-3.5/pygraphviz/graphviz_wrap.o -lcgraph -lcdt -o build/lib.linux-x86_64-3.5/pygraphviz/_graphviz.cpython-35m-x86_64-linux-gnu.so
copying build/lib.linux-x86_64-3.5/pygraphviz/_graphviz.cpython-35m-x86_64-linux-gnu.so -> pygraphviz
/home/aric/localtmp/pygraphviz-1.3.1/.eggs/nose-1.3.7-py3.5.egg/nose/config.py:264: RuntimeWarning: Option 'with-doctest' in config file 'setup.cfg' ignored: excluded by runtime environment
  warn(msg, RuntimeWarning)
/home/aric/localtmp/pygraphviz-1.3.1/.eggs/nose-1.3.7-py3.5.egg/nose/config.py:264: RuntimeWarning: Option 'with-id' in config file 'setup.cfg' ignored: excluded by runtime environment
  warn(msg, RuntimeWarning)
/home/aric/localtmp/pygraphviz-1.3.1/.eggs/nose-1.3.7-py3.5.egg/nose/config.py:264: RuntimeWarning: Option 'doctest-extension' in config file 'setup.cfg' ignored: excluded by runtime environment
  warn(msg, RuntimeWarning)
pygraphviz.tests.test_attribute_defaults.test_default_attributes ... /home/aric/localtmp/pygraphviz-1.3.1/pygraphviz/agraph.py:1741: PendingDeprecationWarning: generator 'Attribute.iteritems' raised StopIteration
  for (k, v) in self.iteritems():
/home/aric/localtmp/pygraphviz-1.3.1/pygraphviz/tests/test_attribute_defaults.py:14: PendingDeprecationWarning: generator 'Attribute.iteritems' raised StopIteration
  assert_equal(sorted(list(A.graph_attr.iteritems())),
ok
pygraphviz.tests.test_attribute_defaults.test_graph_defaults ... ok
pygraphviz.tests.test_attribute_defaults.test_node_defaults ... /home/aric/localtmp/pygraphviz-1.3.1/pygraphviz/tests/test_attribute_defaults.py:57: PendingDeprecationWarning: generator 'Attribute.iteritems' raised StopIteration
  assert_equal(list(A.node_attr.iteritems()), [('label', 'test')])
ok
pygraphviz.tests.test_attribute_defaults.test_edge_defaults ... /home/aric/localtmp/pygraphviz-1.3.1/pygraphviz/tests/test_attribute_defaults.py:97: PendingDeprecationWarning: generator 'Attribute.iteritems' raised StopIteration
  assert_equal(list(A.edge_attr.iteritems()), [('label', 'test')])
ok
pygraphviz.tests.test_clear.test_del ... ok
pygraphviz.tests.test_clear.test_clear_node_with_attributes ... /home/aric/localtmp/pygraphviz-1.3.1/pygraphviz/agraph.py:734: PendingDeprecationWarning: generator 'AGraph.out_edges_iter' raised StopIteration
  for e in self.out_edges_iter(keys=keys):
/home/aric/localtmp/pygraphviz-1.3.1/pygraphviz/agraph.py:388: PendingDeprecationWarning: generator 'AGraph.nodes_iter' raised StopIteration
  return list(self.nodes_iter())
ok
pygraphviz.tests.test_clear.test_clear_graph_attributes ... ok
pygraphviz.tests.test_drawing.test_drawing_error ... ok
pygraphviz.tests.test_drawing.test_name_error ... ok
pygraphviz.tests.test_edge_attributes.test_edge_attributes ... ok
pygraphviz.tests.test_edge_attributes.test_edge_attributes2 ... /home/aric/localtmp/pygraphviz-1.3.1/pygraphviz/agraph.py:1741: PendingDeprecationWarning: generator 'ItemAttribute.iteritems' raised StopIteration
  for (k, v) in self.iteritems():
ok
pygraphviz.tests.test_edge_attributes.test_edge_attribute_update ... ok
pygraphviz.tests.test_edge_attributes.test_edge_attribute_update_nonstrict ... ok
pygraphviz.tests.test_graph.TestDiGraphOnly.test_add_cycle ... ok
pygraphviz.tests.test_graph.TestDiGraphOnly.test_add_edge ... ok
pygraphviz.tests.test_graph.TestDiGraphOnly.test_add_path ... ok
pygraphviz.tests.test_graph.TestDiGraphOnly.test_add_remove_edges_from ... ok
pygraphviz.tests.test_graph.TestDiGraphOnly.test_add_remove_node ... ok
pygraphviz.tests.test_graph.TestDiGraphOnly.test_add_remove_nodes_from ... ok
pygraphviz.tests.test_graph.TestDiGraphOnly.test_clear ... ok
pygraphviz.tests.test_graph.TestDiGraphOnly.test_contains ... ok
pygraphviz.tests.test_graph.TestDiGraphOnly.test_copy ... /home/aric/localtmp/pygraphviz-1.3.1/pygraphviz/tests/test_graph.py:215: ResourceWarning: unclosed file <_io.BufferedRandom name=4>
  A = self.P3.copy()
ok
pygraphviz.tests.test_graph.TestDiGraphOnly.test_data ... ok
pygraphviz.tests.test_graph.TestDiGraphOnly.test_degree ... /home/aric/localtmp/pygraphviz-1.3.1/pygraphviz/agraph.py:835: PendingDeprecationWarning: generator 'AGraph.nodes_iter' raised StopIteration
  bunch = [n for n in self.nodes_iter()]
/home/aric/localtmp/pygraphviz-1.3.1/pygraphviz/agraph.py:840: PendingDeprecationWarning: generator 'AGraph.nodes_iter' raised StopIteration
  bunch = [Node(self, n) for n in nbunch if n in self]
ok
pygraphviz.tests.test_graph.TestDiGraphOnly.test_edge ... ok
pygraphviz.tests.test_graph.TestDiGraphOnly.test_edges ... /home/aric/localtmp/pygraphviz-1.3.1/pygraphviz/agraph.py:761: PendingDeprecationWarning: generator 'AGraph.out_edges_iter' raised StopIteration
  return list(self.out_edges_iter(nbunch=nbunch, keys=keys))
/home/aric/localtmp/pygraphviz-1.3.1/pygraphviz/tests/test_graph.py:293: PendingDeprecationWarning: generator 'AGraph.out_edges_iter' raised StopIteration
  assert_equal(sorted([tuple(sorted(e)) for e in A.out_edges_iter()]),
/home/aric/localtmp/pygraphviz-1.3.1/pygraphviz/agraph.py:768: PendingDeprecationWarning: generator 'AGraph.in_edges_iter' raised StopIteration
  return list(self.in_edges_iter(nbunch=nbunch, keys=keys))
/home/aric/localtmp/pygraphviz-1.3.1/pygraphviz/tests/test_graph.py:297: PendingDeprecationWarning: generator 'AGraph.in_edges_iter' raised StopIteration
  assert_equal(sorted([tuple(sorted(e)) for e in A.in_edges_iter()]),
/home/aric/localtmp/pygraphviz-1.3.1/pygraphviz/tests/test_graph.py:300: PendingDeprecationWarning: generator 'AGraph.out_edges_iter' raised StopIteration
  assert_equal(sorted(A.out_edges_iter(1)), [('1', '2')])
/home/aric/localtmp/pygraphviz-1.3.1/pygraphviz/tests/test_graph.py:302: PendingDeprecationWarning: generator 'AGraph.in_edges_iter' raised StopIteration
  assert_equal(sorted(A.in_edges_iter(2)), [('1', '2')])
/home/aric/localtmp/pygraphviz-1.3.1/pygraphviz/agraph.py:821: PendingDeprecationWarning: generator 'AGraph.predecessors_iter' raised StopIteration
  return list(self.predecessors_iter(n))
/home/aric/localtmp/pygraphviz-1.3.1/pygraphviz/tests/test_graph.py:304: PendingDeprecationWarning: generator 'AGraph.predecessors_iter' raised StopIteration
  assert_equal(list(A.predecessors_iter(1)),[])
/home/aric/localtmp/pygraphviz-1.3.1/pygraphviz/tests/test_graph.py:306: PendingDeprecationWarning: generator 'AGraph.predecessors_iter' raised StopIteration
  assert_equal(list(A.predecessors_iter(2)), ['1'])
/home/aric/localtmp/pygraphviz-1.3.1/pygraphviz/agraph.py:816: PendingDeprecationWarning: generator 'AGraph.successors_iter' raised StopIteration
  return list(self.successors_iter(n))
/home/aric/localtmp/pygraphviz-1.3.1/pygraphviz/tests/test_graph.py:308: PendingDeprecationWarning: generator 'AGraph.successors_iter' raised StopIteration
  assert_equal(list(A.successors_iter(1)), ['2'])
/home/aric/localtmp/pygraphviz-1.3.1/pygraphviz/tests/test_graph.py:310: PendingDeprecationWarning: generator 'AGraph.successors_iter' raised StopIteration
  assert_equal(list(A.successors_iter(2)), ['3'])
ok
pygraphviz.tests.test_graph.TestDiGraphOnly.test_equal ... ok
pygraphviz.tests.test_graph.TestDiGraphOnly.test_get_node ... ok
pygraphviz.tests.test_graph.TestDiGraphOnly.test_getitem ... /home/aric/localtmp/pygraphviz-1.3.1/pygraphviz/agraph.py:609: PendingDeprecationWarning: generator 'AGraph.neighbors_iter' raised StopIteration
  return list(self.neighbors_iter(n))
ok
pygraphviz.tests.test_graph.TestDiGraphOnly.test_graph_not_strict ... ok
pygraphviz.tests.test_graph.TestDiGraphOnly.test_graph_strict ... ok
pygraphviz.tests.test_graph.TestDiGraphOnly.test_has_edge ... /home/aric/localtmp/pygraphviz-1.3.1/pygraphviz/tests/test_graph.py:175: ResourceWarning: unclosed file <_io.BufferedRandom name=4>
  A = self.P3.copy()
ok
pygraphviz.tests.test_graph.TestDiGraphOnly.test_has_node ... ok
pygraphviz.tests.test_graph.TestDiGraphOnly.test_iter ... /home/aric/localtmp/pygraphviz-1.3.1/pygraphviz/tests/test_graph.py:58: PendingDeprecationWarning: generator 'AGraph.nodes_iter' raised StopIteration
  assert_equal(sorted(list(self.P3.__iter__())), ['1', '2', '3'])
/home/aric/localtmp/pygraphviz-1.3.1/pygraphviz/tests/test_graph.py:59: PendingDeprecationWarning: generator 'AGraph.nodes_iter' raised StopIteration
  assert_equal(sorted(self.P3), ['1', '2', '3'])
ok
pygraphviz.tests.test_graph.TestDiGraphOnly.test_len ... ok
pygraphviz.tests.test_graph.TestDiGraphOnly.test_missing_getitem ... ok
pygraphviz.tests.test_graph.TestDiGraphOnly.test_name ... ok
pygraphviz.tests.test_graph.TestDiGraphOnly.test_neighbors ... /home/aric/localtmp/pygraphviz-1.3.1/pygraphviz/tests/test_graph.py:185: PendingDeprecationWarning: generator 'AGraph.neighbors_iter' raised StopIteration
  assert_equal(sorted(A.neighbors_iter(2)), ['1', '3'])
/home/aric/localtmp/pygraphviz-1.3.1/pygraphviz/tests/test_graph.py:186: PendingDeprecationWarning: generator 'AGraph.neighbors_iter' raised StopIteration
  assert_equal(sorted(A.iterneighbors(2)), ['1', '3'])
ok
pygraphviz.tests.test_graph.TestDiGraphOnly.test_nodes ... /home/aric/localtmp/pygraphviz-1.3.1/pygraphviz/tests/test_graph.py:103: PendingDeprecationWarning: generator 'AGraph.nodes_iter' raised StopIteration
  assert_equal(sorted(self.P3.nodes_iter()),['1', '2', '3'])
/home/aric/localtmp/pygraphviz-1.3.1/pygraphviz/tests/test_graph.py:104: PendingDeprecationWarning: generator 'AGraph.nodes_iter' raised StopIteration
  assert_equal(sorted(self.P3.iternodes()),['1', '2', '3'])
ok
pygraphviz.tests.test_graph.TestDiGraphOnly.test_order ... ok
pygraphviz.tests.test_graph.TestDiGraphOnly.test_remove_edges_from ... ok
pygraphviz.tests.test_graph.TestDiGraphOnly.test_repr ... ok
pygraphviz.tests.test_graph.TestDiGraphOnly.test_size ... ok
pygraphviz.tests.test_graph.TestDiGraphOnly.test_str ... ok
pygraphviz.tests.test_graph.TestDiGraphOnly.test_strict ... ok
pygraphviz.tests.test_graph.TestGraph.test_add_cycle ... ok
pygraphviz.tests.test_graph.TestGraph.test_add_edge ... ok
pygraphviz.tests.test_graph.TestGraph.test_add_path ... ok
pygraphviz.tests.test_graph.TestGraph.test_add_remove_edges_from ... ok
pygraphviz.tests.test_graph.TestGraph.test_add_remove_node ... ok
pygraphviz.tests.test_graph.TestGraph.test_add_remove_nodes_from ... ok
pygraphviz.tests.test_graph.TestGraph.test_clear ... ok
pygraphviz.tests.test_graph.TestGraph.test_contains ... ok
pygraphviz.tests.test_graph.TestGraph.test_copy ... ok
pygraphviz.tests.test_graph.TestGraph.test_data ... ok
pygraphviz.tests.test_graph.TestGraph.test_degree ... ok
pygraphviz.tests.test_graph.TestGraph.test_edges ... ok
pygraphviz.tests.test_graph.TestGraph.test_equal ... ok
pygraphviz.tests.test_graph.TestGraph.test_get_node ... ok
pygraphviz.tests.test_graph.TestGraph.test_getitem ... ok
pygraphviz.tests.test_graph.TestGraph.test_graph_not_strict ... ok
pygraphviz.tests.test_graph.TestGraph.test_graph_strict ... ok
pygraphviz.tests.test_graph.TestGraph.test_has_edge ... ok
pygraphviz.tests.test_graph.TestGraph.test_has_node ... ok
pygraphviz.tests.test_graph.TestGraph.test_iter ... ok
pygraphviz.tests.test_graph.TestGraph.test_len ... ok
pygraphviz.tests.test_graph.TestGraph.test_missing_getitem ... ok
pygraphviz.tests.test_graph.TestGraph.test_neighbors ... ok
pygraphviz.tests.test_graph.TestGraph.test_nodes ... ok
pygraphviz.tests.test_graph.TestGraph.test_order ... ok
pygraphviz.tests.test_graph.TestGraph.test_remove_edges_from ... ok
pygraphviz.tests.test_graph.TestGraph.test_repr ... ok
pygraphviz.tests.test_graph.TestGraph.test_size ... ok
pygraphviz.tests.test_graph.TestGraph.test_str ... ok
pygraphviz.tests.test_graph.TestGraph.test_strict ... ok
pygraphviz.tests.test_html.test_html ... ok
pygraphviz.tests.test_layout.test_layout ... ok
pygraphviz.tests.test_node_attributes.test_node_attribute ... ok
pygraphviz.tests.test_node_attributes.test_node_attributes2 ... ok
pygraphviz.tests.test_node_attributes.test_node_attribute_update ... ok
pygraphviz.tests.test_node_attributes.test_node_attribute_remove ... ok
pygraphviz.tests.test_readwrite.test_readwrite ... ok
pygraphviz.tests.test_string.test_name ... ok
pygraphviz.tests.test_string.test_string_representation_small ... ok
pygraphviz.tests.test_string.test_string_representation_large ... ok
pygraphviz.tests.test_string.test_bad_dot_input ... Error: syntax error in line 36 near ''
/home/aric/localtmp/pygraphviz-1.3.1/.eggs/nose-1.3.7-py3.5.egg/nose/tools/nontrivial.py:62: ResourceWarning: unclosed file <_io.BufferedRandom name=4>
  pass
ok
pygraphviz.tests.test_subgraph.test_subgraph ... ok
pygraphviz.tests.test_subgraph.test_subgraph_cluster ... ok
pygraphviz.tests.test_subgraph.test_subgraph_cluster_attribute ... ok
pygraphviz.tests.test_unicode.test_name_unicode ... ok
pygraphviz.tests.test_unicode.test_node_encoding ... ok
pygraphviz.tests.test_unicode.test_edge_encoding ... ok
pygraphviz.tests.test_unicode.test_from_string ... ok

----------------------------------------------------------------------
Ran 93 tests in 0.677s

OK
```

**Comment by jamadden** [comment] 2016-07-29 19:10
A new enough swig does support PyPy. See #75.

**Comment by teh** [comment] 2016-10-27 08:47
I think this was fixed by https://github.com/pygraphviz/pygraphviz/commit/3bfd9238613153ccf1c7898ed7eeafdf7e1aefca

should be OK to close.

**Closed** 2016-11-04 23:32 UTC
