### ISSUE TITLE
Pygraphviz crashes after drawing 170 graphs on Windows

### ISSUE THREAD

**Issue by dhonig26** [pygraphviz/pygraphviz#213] opened 2020-03-26 23:08 UTC
I am using pygraphviz to create a large number of graphs for different configurations of data. I have found that no matter what information is put in the graph the program will crash after drawing the 170th graph. There are no error messages generated the program just stops. Is there something that needs to be reset if drawing this many graphs?

I am running Python 3.7 on a Windows 10 machine, Pygraphviz 1.5, and graphviz 2.38

    for graph_number in range(200):
        config_graph = pygraphviz.AGraph(strict=False, directed=False, compound=True, ranksep='0.2', nodesep='0.2')

        # Create Directory
        if not os.path.exists('Graph'):
            os.makedirs('Graph')

        # Draw Graph      
        print('draw_' + str(graph_number))
        config_graph.layout(prog = 'dot')
        config_graph.draw('Graph/'+str(graph_number)+'.png')

**Comment by CristiFati** [comment] 2020-04-06 08:37
Check [\[SO\]: Pygraphviz crashes after drawing 170 graphs (@CristiFati's answer)](https://stackoverflow.com/questions/60876623/pygraphviz-crashes-after-drawing-170-graphs/61050313#61050313).

**Comment by denisesato** [comment] 2021-05-12 13:45
I am still getting the problem. My app crashes because pygraphviz does not release the file handles correctly on my Windows 10 machine. Could someone help me with this?

**Comment by rossbar** [comment] 2021-05-12 16:35
Thanks for the report @denisesato , I'm going to reopen this and modify the title a bit since this seems to be related to file handling on Windows specifically.

It's not clear to me whether this is an issue with pygraphviz or with GraphViz `cgraph` (or maybe even Windows itself). I think a sensible way to start chasing this down would be to:
 1. Add a test to the test suite for this case. A pared-down version of the [example you've provided in the other thread](https://github.com/pygraphviz/pygraphviz/pull/216#issuecomment-839808726) would work nicely.
 2. My initial feeling is to start looking around where/how `agwrite` and `agread` (and maybe also `agconcat`) are called in pygraphviz, as these are the main functions responsible for I/O AFAICT. There may be something in pygraphviz itself that jumps out as problematic - if not, then opening a related issue in GraphViz with the findings from this investigation is probably the right move.

I plan on running through the above procedure as soon as I have time, but anyone who's interested please don't hesitate to take a stab.

Link to relevant discussion in another thread: https://github.com/pygraphviz/pygraphviz/pull/216#issuecomment-839784411

**Comment by denisesato** [comment] 2021-05-20 12:19
Hello @rossbar, 
   
   Did you have time for checking this issue?

Thanks in advance,
Denise

**Comment by nehaljwani** [comment] 2022-06-06 05:06
Minimal steps to reproduce the problem with `pygraphviz`:

```python
import pygraphviz as pgv

for _ in range(512):
    pgv.AGraph("digraph {1 -> 2}")
```

Proposed workaround till a fix is merged and released:
```python
# pywin32 package
import win32file as wfile

# Set to something above wfile._getmaxstdio(), according to your needs
wfile._setmaxstdio(513)
```

Minimal steps to reproduce the problem **without** `graphviz`:
```python
# Create a module called 'testcase'
$ cat testcase.c
#include "Python.h"

/* int testcase(int, int) */
static PyObject *py_testcase(PyObject *self, PyObject *args) {

  PyObject *x;
  int y;
  if (!PyArg_ParseTuple(args, "Oi", &x, &y)) {
    return NULL;
  }
  int fd1 = PyObject_AsFileDescriptor(x);

  FILE *fp = fdopen(fd1, "r");

  if (fp == NULL) {
    printf("Oh No! Death@%d\n", y);
    exit(-1);
  }

  Py_RETURN_NONE;
}

/* Module method table */
static PyMethodDef TestcaseMethods[] = {
    {"testcase", py_testcase, METH_VARARGS, "testcase"}, {NULL, NULL, 0, NULL}};

/* Module structure */
static struct PyModuleDef testcasemodule = {
    PyModuleDef_HEAD_INIT, "testcase", /* name of module */
    "A testcase module",               /* Doc string (may be NULL) */
    -1,                                /* Size of per-interpreter state or -1 */
    TestcaseMethods                    /* Method table */
};

/* Module initialization function */
PyMODINIT_FUNC PyInit_testcase(void) {
  return PyModule_Create(&testcasemodule);
}

$ cat setup.py
from distutils.core import setup, Extension

setup(
    name="testcase", version="1.0", ext_modules=[Extension("testcase", ["testcase.c"])]
)

# Build the 'testcase' module
$ python setup.py build

# Run a our beloved testcase against the 'testcase' module
$ cd build\lib.win-amd64-3.8

$ cat test.py
import testcase
import tempfile
for i in range(1000):
   fh = tempfile.TemporaryFile()
   testcase.testcase(fh, i)
   fh.close()

$ python test.py
Oh No! Death@509
```

The issue goes away with this patch:
```diff
$ diff -u testcase.*
--- testcase.c  2022-06-06 00:47:59.995310200 -0400
+++ testcase.withfix.c  2022-06-06 00:47:47.023409000 -0400
@@ -10,13 +10,15 @@
   }
   int fd1 = PyObject_AsFileDescriptor(x);

-  FILE *fp = fdopen(fd1, "r");
+  FILE *fp = fdopen(dup(fd1), "r");

   if (fp == NULL) {
     printf("Oh No! Death@%d\n", y);
     exit(-1);
   }

+  fclose(fp);
+
   Py_RETURN_NONE;
 }
```

Not sure if this is the most optimal fix, but I've opened a PR at https://github.com/pygraphviz/pygraphviz/pull/415

**Closed** 2022-08-09 16:36 UTC
